# -*- coding: utf-8 -*-
"""Python Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J24X4GgXV9ibdbD0B5zPwyYz5hTaFyiS
"""

def calculator(a, b, operator):
    try:
        if operator == "+":
            return a + b
        elif operator == "-":
            return a - b
        elif operator == "*":
            return a * b
        elif operator == "/":
            return a / b
        else:
            raise ValueError(f"Unknown operator: {operator}")
    except ZeroDivisionError:
        return "Error: Division by zero"
    except ValueError as e:
        return f"Error: {e}"


result = calculator(5, 3, "+")
print(result)
result=calculator (2,5,"*")
print (result)
result=calculator(3,7,"-")
print (result)

def even_odd_checker(n):
    return "Even" if n % 2 == 0 else "Odd"


# --- Run it ---
print(f"7 is {even_odd_checker(7)}")
print(f"10 is {even_odd_checker(10)}")
print(f"23 is {even_odd_checker(23)}")

def largest_number(numbers):
    if not numbers:
        raise ValueError("List is empty")
    largest = numbers[0]
    for num in numbers:
        if num > largest:
            largest = num
    return largest


nums = [4, 9, 2, 7, 15, 3]
print("List:", nums)
print("Largest number:", largest_number(nums))

nums = [5, 3, 8, 1, 9, 2]
print("Original list:", nums)

nums.append(10)
print("After append(10):", nums)

nums.remove(3)
print("After remove(3):", nums)

nums.sort()
print("After sort():", nums)

evens = [n for n in nums if n % 2 == 0]
print("Filtered evens:", evens)

student = {"name": "Alice", "age": 20, "course": "Python"}
print("Original dict:", student)

student["grade"] = "A"  # add key
print("After adding grade:", student)

student["age"] = 21  # update key
print("After updating age:", student)

del student["course"]  # delete key
print("After deleting course:", student)

def student_grade_calculator(marks):
    """marks: dict of subject -> score (0-100)"""
    if not marks:
        raise ValueError("No marks provided")

    total = sum(marks.values())
    average = total / len(marks)

    if average >= 90:
        grade = "A"
    elif average >= 75:
        grade = "B"
    elif average >= 60:
        grade = "C"
    elif average >= 40:
        grade = "D"
    else:
        grade = "F"

    return {"total": total, "average": round(average, 2), "grade": grade}



marks = {"Math": 85, "Science": 92, "English": 78}
result = student_grade_calculator(marks)
print("Marks:", marks)
print("Result:", result)

def factorial(n):
    if n < 0:
        raise ValueError("Factorial not defined for negative numbers")
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result


def reverse_string(s):
    return s[::-1]


def is_palindrome(s):
    cleaned = s.replace(" ", "").lower()
    return cleaned == cleaned[::-1]



print("5! =", factorial(5))
print("Reverse of 'python':", reverse_string("python"))
print("Is 'madam' a palindrome?", is_palindrome("madam"))
print("Is 'hello' a palindrome?", is_palindrome("hello"))

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional

app = FastAPI(title="Student API")


class Student(BaseModel):
    name: str
    age: int
    course: str


class StudentUpdate(BaseModel):
    name: Optional[str] = None
    age: Optional[int] = None
    course: Optional[str] = None


students: dict[int, Student] = {
    1: Student(name="Alice", age=20, course="Python"),
    2: Student(name="Bob", age=22, course="FastAPI"),
}
next_id = 3


@app.get("/")
def root():
    return {"message": "Welcome to the Student API"}


@app.get("/students")
def get_students():
    return students


@app.get("/students/{student_id}")
def get_student(student_id: int):
    if student_id not in students:
        raise HTTPException(status_code=404, detail="Student not found")
    return students[student_id]


@app.get("/students/search/")
def search_students(course: Optional[str] = None):
    if course is None:
        return students
    return {
        sid: s for sid, s in students.items() if s.course.lower() == course.lower()
    }


@app.post("/students")
def create_student(student: Student):
    global next_id
    students[next_id] = student
    new_id = next_id
    next_id += 1
    return {"id": new_id, "student": student}


@app.put("/students/{student_id}")
def update_student(student_id: int, update: StudentUpdate):
    if student_id not in students:
        raise HTTPException(status_code=404, detail="Student not found")

    stored = students[student_id]
    updated_data = stored.dict()
    for field, value in update.dict(exclude_unset=True).items():
        updated_data[field] = value

    students[student_id] = Student(**updated_data)
    return students[student_id]


@app.delete("/students/{student_id}")
def delete_student(student_id: int):
    if student_id not in students:
        raise HTTPException(status_code=404, detail="Student not found")
    deleted = students.pop(student_id)
    return {"message": f"Deleted student {student_id}", "student": deleted}